DELETE FROM CLIENTES WHERE CEDULA=1234
DELETE FROM PRODUCTOS WHERE CODIGO=716523
DELETE FROM AFILIADOS WHERE CEDULA_AFILIADO=1234
DELETE FROM AFILIADOS WHERE CEDULA_AFILIADO=123
DELETE FROM CIUDADES WHERE CODIGO=123
DELETE FROM DEPARTAMENTOS WHERE CODIGO=123
DELETE FROM PAISES WHERE CODIGO=123